"""empty message

Revision ID: a74e7c1077c3
Revises: 932a14e35537
Create Date: 2022-11-29 22:57:21.364405

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a74e7c1077c3'
down_revision = '932a14e35537'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csv_position_py',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('positionName', sa.String(length=255), nullable=False),
                    sa.Column('address', sa.String(length=255), nullable=False),
                    sa.Column('publishtime', sa.String(length=255), nullable=True),
                    sa.Column('money', sa.String(length=255), nullable=False),
                    sa.Column('education', sa.String(length=255), nullable=False),
                    sa.Column('posturl', sa.String(length=255), nullable=False),
                    sa.Column('jobNature', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('csv_position')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csv_position',
                    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
                    sa.Column('positionName', mysql.VARCHAR(length=255), nullable=False),
                    sa.Column('address', mysql.VARCHAR(length=255), nullable=False),
                    sa.Column('publishtime', mysql.VARCHAR(length=255), nullable=True),
                    sa.Column('money', mysql.VARCHAR(length=255), nullable=False),
                    sa.Column('education', mysql.VARCHAR(length=255), nullable=False),
                    sa.Column('posturl', mysql.VARCHAR(length=800), nullable=False),
                    sa.Column('jobNature', mysql.VARCHAR(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_default_charset='utf8',
                    mysql_engine='InnoDB'
                    )
    op.drop_table('csv_position_py')
    # ### end Alembic commands ###
